version: '3.8'

services:
  bot:
    build:
      context: ../src
      dockerfile: ../deploy/botpy/Dockerfile
    container_name: GeologPy
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    container_name: redis_stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
