services:
  bot:
    build:
      context: ../src
      dockerfile: ../deploy/botpy/Dockerfile
    container_name: GeologPy
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TELE_BOT_TOKEN=${TELE_BOT_TOKEN}
    restart: unless-stopped

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_stack
    # ports:
    #  - "6379:6379"
    environment:
      - REDIS_ARGS=--maxmemory 256mb
    volumes:
      - ./redis_data:/data
    restart: unless-stopped

# volumes:
#    redis_data:
