version: '3.8'

services:
  bot:
    build: ./botpy  # Path to the directory with your Python bot's Dockerfile
    container_name: GeologPy
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    container_name: redis_stack
    ports:
      - "6379:6379"    # Redis
      - "8001:8001"    # RedisInsight (Web UI)
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
