name: Run Tests with Docker Compose

on:
  push:
    branches: [ main, tmp/gh-action ]
  pull_request:
    branches: [ main, tmp/gh-action ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run tests via makefile
        working-directory: ./src
        run: make test-docker
